2단계 - Proxy와 Bean 의존관계
next-step/java-aop pull request #4
Opened 2024-08-18 16:11 UTC by jinyoungchoi95

안녕하세요 동철님 🙂

리뷰 감사합니다 🙇‍♂️

2024-08-20 00:50 UTC, sah3122 requested changes
2단계 미션 구현 잘해주셨습니다 👍 
깔끔한 코드가 인상적이네요 ! 
한가지 도전 과제를 남겨두었는데 확인 부탁드려요 🙏

2024-08-20 00:50 UTC, sah3122 commented on aop/src/test/java/com/interface21/beans/factory/proxy/ProxyFactoryBeanTest.java
> +    void 프록시빈을_생성한다() {
테스트 코드를 보니 작성해주신 Advice, Advisor 등의 역할이 잘 이해 되는것 같습니다 👍 
깔끔하게 작성 잘해주셨네요 😄

2024-08-20 00:50 UTC, sah3122 commented on di/src/main/java/com/interface21/beans/factory/support/DefaultListableBeanFactory.java
> +        if (bean instanceof FactoryBean<?> factoryBean) {
FactoryBean 타입에 대해 Bean 등록 잘해주셨습니다 👍 
이처럼 등록될수 있는 FactoryBean에 대한 Production 코드를 추가해보는건 어떨까요 ?

2024-08-20 00:50 UTC, sah3122 commented on aop/src/main/java/com/interface21/beans/factory/proxy/Advisor.java
> +            if (pointCut.matches(method)) {
pointCut 의 실행 시점이 고정되어 있는것 같습니다 😄 
Before, After와 같이 실행 시점을 지정할수 있도록 구조를 잡아두는것도 좋은 경험이 될것 같습니다 👍

2024-08-20 14:21 UTC, jinyoungchoi95 commented on di/src/main/java/com/interface21/beans/factory/support/DefaultListableBeanFactory.java
> +        if (bean instanceof FactoryBean<?> factoryBean) {
테스트에 Configuration 추가해서 테스트해보았습니다 :)

https://github.com/next-step/java-aop/pull/4/commits/7ee829497c0abffcd4b6155706113af0e3075bd6

2024-08-20 14:22 UTC, jinyoungchoi95 commented on aop/src/main/java/com/interface21/beans/factory/proxy/Advisor.java
> +            if (pointCut.matches(method)) {
`AfterAdvice`, `BeforeAdvice` 추가했습니다 😄

2024-08-20 14:24 UTC, jinyoungchoi95 commented
안녕하세요 동철님 🙂

리뷰 감사합니다 🙇‍♂️

2024-08-21 09:05 UTC, sah3122 approved these changes
어려울수도 있는 과제였는데 반영 잘해주셨습니다 👍 
다음 미션도 화이팅 해주세요 !

2024-08-21 09:05 UTC, sah3122 commented on aop/src/main/java/com/interface21/beans/factory/proxy/AfterAdvice.java
> +public abstract class AfterAdvice implements Advice {
피드백 반영 잘해주셨습니다 👍

2024-08-21 09:05 UTC, sah3122 commented on aop/src/test/java/com/interface21/beans/factory/proxy/BeforeAdviceTest.java
> +    void joinPoint를_실행하기_전_before를_먼저_실행한다() throws Throwable {
테스트 코드 깔끔하게 작성 잘해주셨네요 💯

2024-08-21 09:05 UTC, sah3122 commented on aop/src/main/java/com/interface21/beans/factory/proxy/AfterAdvice.java
> +    abstract void afterReturning(Object returnValue, Method method, Object[] args);
현재는 추상 클래스로 구현해주셨는데 Advice를 실행하는 구현체를 하나 두고, 다양한 Advice를 적용할수 있는 구조도 적용해볼만 하겠네요 😄

2024-08-21 09:05 UTC, merged